id: P942F2FAA
initial_creation_type: input
source_metadata:
  title: Hayagrīva Series
  language: en
  description: 'Texts related to Hayagrīva (rta mgrin), a wrathful manifestation of
    Avalokiteśvara who symbolizes enlightened speech and is usually depicted with
    a horse''s head protruding from his crown:'
  volume:
    783813b5c7a4404ab352b2d4fb6f2a63:
      title: Fulfilment Offering for Nyangrel Nyima Özer's Treasure Practice of Black
        Hayagrīva with an Iron Sword
      parent: Black Hayagrīva
    f477bd6ea3d4444dab356af1fd6f4425:
      title: Prayer to the Lineage of the Supreme Hayagrīva Emanation from the Aural
        Transmission
      parent: Lineage Prayers
    d468d2dcd09b4a718f9dc1d712192af8:
      title: Daily Practice of Hayagrīva
      parent: Sādhanas
    218a85216867417cb51c7f71eea49bf0:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Sādhanas
created_at: '2022-03-01T03:56:44.292561'
last_modified_at: '2022-03-01T03:56:44.292570'
